- name: Upload bagit ZIP package
  copy:
    src: "bagit-{{ bagit_version }}.zip"
    dest: "{{ ansible_user_dir }}"

- name: Create a provider dir for gov.loc
  file:
    path: "/opt/gov.loc/"
    state: directory

- name: Unzip to /opt
  unarchive:
    src: "{{ ansible_user_dir }}/bagit-{{ bagit_version }}.zip"
    remote_src: yes
    dest: "/opt/gov.loc/"
    creates: "/opt/gov.loc/bagit-{{ bagit_version }}"

- name: Create directory for bagit logging
  file:
    path: "/var/opt/gov.loc/log/bagit"
    state: directory
    mode: "0777"

- name: Configure logging for bagit
  replace:
    path: "/opt/gov.loc/bagit-{{ bagit_version }}/conf/log4j.properties"
    regexp: 'log4j.appender.R.File=.*$'
    replace: "log4j.appender.R.File=/var/opt/gov.loc/log/bagit/bagit.log"

- name: Put bagit on path
  file:
    src: "/opt/gov.loc/bagit-{{ bagit_version }}/bin/bagit"
    dest: "/opt/bin/bagit"
    state: link
