Vagrant.configure(2) do |config|
   config.vm.define "tutorial", primary: true do |tutorial|
      tutorial.vm.box = "geerlingguy/centos7"
      tutorial.vm.box_version = "1.2.16"
      tutorial.vm.hostname = "tutorial"
      tutorial.vm.network :private_network, ip: "192.168.33.32"
   end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "tutorial-vm.yml"
      ansible.config_file = "ansible.cfg"
      ansible.compatibility_mode = "2.0"
   end

   config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 3072
      vb.cpus = 2
      vb.customize ["guestproperty", "set", :id, "--timesync-threshold", "1000"]
      vb.customize ["guestproperty", "set", :id, "--timesync-interval", "1000"]
   end
end
